[project]
name = "fastapi-error-handling-demo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "structlog>=25.1.0",
    "uvicorn>=0.34.0",
    "starlette==0.45.3",
]
